import type {
  DashboardData,
  Hotspot,
  InjuryItem,
  MarketMover,
  MatchMarketMover,
  NewsItem,
  PredictionMarket,
  TransferMarketMover,
} from "./types";

const matchMovers: MatchMarketMover[] = [
  {
    id: "match-mci-rma-rodri",
    title: "City midfield injury shock moves Madrid price",
    summary:
      "A late training absence before a Champions League match pushes the Madrid draw-no-bet market into heavier demand.",
    league: "Champions League",
    club: "Manchester City",
    player: "Rodri",
    marketType: "match",
    severity: "Shock",
    sourceTier: "Tier 1",
    region: "England",
    timestamp: "2026-05-08T14:42:00Z",
    displayTime: "10:42",
    impact: "Model win probability moved from 54% to 48% after availability risk.",
    relatedSource: "Club availability briefing",
    fixture: "Manchester City vs Real Madrid",
    probabilityBefore: 54,
    probabilityAfter: 48,
    oddsDirection: "drifting",
    driver: "Late midfield availability concern",
  },
  {
    id: "match-psg-bay-form",
    title: "PSG price shortens after Bayern defensive rotation",
    summary:
      "Projected Bayern back line changes create a fresh attacking mismatch signal for Paris Saint-Germain.",
    league: "Champions League",
    club: "Paris Saint-Germain",
    marketType: "match",
    severity: "Move",
    sourceTier: "Tier 2",
    region: "France",
    timestamp: "2026-05-08T13:58:00Z",
    displayTime: "09:58",
    impact: "PSG implied probability rose four points in the sample model.",
    relatedSource: "Team news desk",
    fixture: "Paris Saint-Germain vs Bayern Munich",
    probabilityBefore: 41,
    probabilityAfter: 45,
    oddsDirection: "shortening",
    driver: "Bayern defensive rotation reports",
  },
  {
    id: "match-liv-ars-salah",
    title: "Liverpool steadies after Salah returns to full session",
    summary:
      "Team news tied to Mohamed Salah's full training involvement slows Arsenal money and supports Liverpool.",
    league: "Premier League",
    club: "Liverpool",
    player: "Mohamed Salah",
    marketType: "match",
    severity: "Monitor",
    sourceTier: "Tier 1",
    region: "England",
    timestamp: "2026-05-08T13:21:00Z",
    displayTime: "09:21",
    impact: "Liverpool moved from 46% to 48% after availability concern eased.",
    relatedSource: "Training ground photo set",
    fixture: "Liverpool vs Arsenal",
    probabilityBefore: 46,
    probabilityAfter: 48,
    oddsDirection: "shortening",
    driver: "Key forward returns to full training",
  },
  {
    id: "match-bar-atm-yamal",
    title: "Barcelona wide rotation creates derby totals watch",
    summary:
      "Expected Lamine Yamal minute protection trims Barcelona attacking projection before Atletico Madrid.",
    league: "La Liga",
    club: "Barcelona",
    player: "Lamine Yamal",
    marketType: "match",
    severity: "Noise",
    sourceTier: "Tier 2",
    region: "Spain",
    timestamp: "2026-05-08T14:15:00Z",
    displayTime: "10:15",
    impact: "Barcelona win probability is stable, but totals tick down one point.",
    relatedSource: "Catalan team news desk",
    fixture: "Barcelona vs Atletico Madrid",
    probabilityBefore: 51,
    probabilityAfter: 50,
    oddsDirection: "stable",
    driver: "Projected minutes management",
  },
  {
    id: "match-psg-om-dembele",
    title: "PSG shortens after Marseille fullback scratch",
    summary:
      "A confirmed Marseille defensive absence adds a domestic match signal to the Paris hotspot.",
    league: "Ligue 1",
    club: "Paris Saint-Germain",
    player: "Ousmane Dembele",
    marketType: "match",
    severity: "Monitor",
    sourceTier: "Tier 2",
    region: "France",
    timestamp: "2026-05-08T12:46:00Z",
    displayTime: "08:46",
    impact: "PSG league win probability edges from 62% to 64%.",
    relatedSource: "French team news desk",
    fixture: "Paris Saint-Germain vs Marseille",
    probabilityBefore: 62,
    probabilityAfter: 64,
    oddsDirection: "shortening",
    driver: "Marseille defensive availability update",
  },
];

const transferMovers: TransferMarketMover[] = [
  {
    id: "transfer-wirtz-arsenal",
    title: "Wirtz links escalate from rumor to direct talks",
    summary:
      "A link that began as a Tier 3 rumor is now carried by a Tier 1 reporter as active negotiation watch.",
    league: "Bundesliga",
    club: "Bayer Leverkusen",
    player: "Florian Wirtz",
    marketType: "transfer",
    severity: "Move",
    sourceTier: "Tier 1",
    region: "Germany",
    timestamp: "2026-05-08T15:06:00Z",
    displayTime: "11:06",
    impact: "Likelihood jumps from 22% to 38% after source-tier upgrade.",
    relatedSource: "Tier 1 transfer reporter",
    linkedClubs: ["Arsenal", "Real Madrid", "Bayern Munich"],
    likelihoodBefore: 22,
    likelihoodAfter: 38,
    feeRange: "EUR110m-EUR135m",
  },
  {
    id: "transfer-osimhen-chelsea",
    title: "Chelsea striker watch returns after Napoli fee signal",
    summary:
      "Fee-range chatter reopens a monitored transfer situation without confirmation from stronger sources.",
    league: "Serie A",
    club: "Napoli",
    player: "Victor Osimhen",
    marketType: "transfer",
    severity: "Monitor",
    sourceTier: "Tier 3",
    region: "Italy",
    timestamp: "2026-05-08T12:34:00Z",
    displayTime: "08:34",
    impact: "Market stays watched until a stronger source confirms negotiations.",
    relatedSource: "Aggregator rumor stack",
    linkedClubs: ["Chelsea", "Paris Saint-Germain"],
    likelihoodBefore: 18,
    likelihoodAfter: 24,
    feeRange: "EUR85m-EUR105m",
  },
  {
    id: "transfer-nico-psg",
    title: "Nico Williams camp contact lifts PSG wing market",
    summary:
      "Spanish and French reports align on initial camp contact, creating a cross-border transfer signal.",
    league: "Ligue 1",
    club: "Paris Saint-Germain",
    player: "Nico Williams",
    marketType: "transfer",
    severity: "Monitor",
    sourceTier: "Tier 2",
    region: "France",
    timestamp: "2026-05-08T15:19:00Z",
    displayTime: "11:19",
    impact: "Likelihood rises from 15% to 27% while Athletic Club stance remains firm.",
    relatedSource: "Paris transfer desk",
    linkedClubs: ["Paris Saint-Germain", "Barcelona", "Chelsea"],
    likelihoodBefore: 15,
    likelihoodAfter: 27,
    feeRange: "EUR58m-EUR70m",
  },
  {
    id: "transfer-maignan-bayern",
    title: "Maignan succession chatter returns around Bayern",
    summary:
      "Goalkeeper succession planning talk adds a low-grade Milan to Munich transfer watch item.",
    league: "Serie A",
    club: "AC Milan",
    player: "Mike Maignan",
    marketType: "transfer",
    severity: "Noise",
    sourceTier: "Tier 3",
    region: "Italy",
    timestamp: "2026-05-08T11:52:00Z",
    displayTime: "07:52",
    impact: "Likelihood nudges from 9% to 13%, below actionable threshold.",
    relatedSource: "Weekend column roundup",
    linkedClubs: ["Bayern Munich", "Manchester United"],
    likelihoodBefore: 9,
    likelihoodAfter: 13,
    feeRange: "EUR40m-EUR55m",
  },
];

const signals: MarketMover[] = [...matchMovers, ...transferMovers];

const predictionMarkets: PredictionMarket[] = [
  {
    id: "pm-rodri-champions",
    question: "Will Rodri play 90 minutes vs Real Madrid?",
    market: "Champions League",
    league: "Champions League",
    outcome: "No",
    probability: 28,
    volume: 892000,
    volumeDisplay: "$892K",
    change24h: -12,
    trend: "falling",
  },
  {
    id: "pm-wirtz-arsenal",
    question: "Will Florian Wirtz transfer to Arsenal this summer?",
    market: "Transfer 2026",
    league: "Bundesliga",
    outcome: "Yes",
    probability: 42,
    volume: 1240000,
    volumeDisplay: "$1.24M",
    change24h: 8,
    trend: "rising",
  },
  {
    id: "pm-psg-bayern",
    question: "Will PSG advance past Bayern Munich?",
    market: "Champions League",
    league: "Champions League",
    outcome: "Yes",
    probability: 61,
    volume: 2150000,
    volumeDisplay: "$2.15M",
    change24h: 3,
    trend: "stable",
  },
  {
    id: "pm-osimhen-chelsea",
    question: "Will Victor Osimhen sign for Chelsea?",
    market: "Transfer 2026",
    league: "Serie A",
    outcome: "Yes",
    probability: 35,
    volume: 678000,
    volumeDisplay: "$678K",
    change24h: -5,
    trend: "falling",
  },
  {
    id: "pm-premier-league",
    question: "Will Liverpool win the Premier League?",
    market: "Premier League",
    league: "Premier League",
    outcome: "Yes",
    probability: 78,
    volume: 3400000,
    volumeDisplay: "$3.4M",
    change24h: 2,
    trend: "stable",
  },
];

const news: NewsItem[] = [
  {
    id: "news-rodri-fitness",
    headline: "City medical staff schedule Rodri decision after closed Champions League session",
    league: "Champions League",
    club: "Manchester City",
    player: "Rodri",
    marketType: "match",
    sourceTier: "Tier 1",
    timestamp: "2026-05-08T14:44:00Z",
    displayTime: "10:44",
    impactTag: "shock injury",
  },
  {
    id: "news-barca-yamal",
    headline: "Barcelona expected to protect Lamine Yamal minutes before Europe",
    league: "La Liga",
    club: "Barcelona",
    player: "Lamine Yamal",
    marketType: "match",
    sourceTier: "Tier 2",
    timestamp: "2026-05-08T14:15:00Z",
    displayTime: "10:15",
    impactTag: "rotation risk",
  },
  {
    id: "news-liverpool-salah",
    headline: "Liverpool training images reduce Salah availability concern",
    league: "Premier League",
    club: "Liverpool",
    player: "Mohamed Salah",
    marketType: "match",
    sourceTier: "Tier 1",
    timestamp: "2026-05-08T13:21:00Z",
    displayTime: "09:21",
    impactTag: "price support",
  },
  {
    id: "news-wirtz-tier-upgrade",
    headline: "Wirtz story upgraded from aggregator rumor to Tier 1 direct talks report",
    league: "Bundesliga",
    club: "Bayer Leverkusen",
    player: "Florian Wirtz",
    marketType: "transfer",
    sourceTier: "Tier 1",
    timestamp: "2026-05-08T15:08:00Z",
    displayTime: "11:08",
    impactTag: "tier upgrade",
  },
  {
    id: "news-napoli-osimhen",
    headline: "Napoli valuation chatter keeps Osimhen watch active but unconfirmed",
    league: "Serie A",
    club: "Napoli",
    player: "Victor Osimhen",
    marketType: "transfer",
    sourceTier: "Tier 3",
    timestamp: "2026-05-08T12:41:00Z",
    displayTime: "08:41",
    impactTag: "fee signal",
  },
];

const injuries: InjuryItem[] = [
  {
    id: "injury-rodri",
    player: "Rodri",
    club: "Manchester City",
    league: "Champions League",
    status: "Late fitness check",
    expectedAbsence: "Matchday decision",
    severity: "Shock",
    marketImpact: "City win probability drifting in sample model before Real Madrid.",
  },
  {
    id: "injury-de-ligt",
    player: "Matthijs de Ligt",
    club: "Bayern Munich",
    league: "Champions League",
    status: "Managed minutes expected",
    expectedAbsence: "Bench risk",
    severity: "Move",
    marketImpact: "PSG attacking projection improves against a rotated Bayern defense.",
  },
  {
    id: "injury-pedri",
    player: "Pedri",
    club: "Barcelona",
    league: "La Liga",
    status: "Training load capped",
    expectedAbsence: "Limited minutes",
    severity: "Monitor",
    marketImpact: "Barcelona totals market remains sensitive to confirmed lineup.",
  },
];

const hotspots: Hotspot[] = [
  {
    id: "hot-manchester",
    city: "Manchester",
    country: "England",
    region: "England",
    league: "Champions League",
    x: 24,
    y: 37,
    intensity: 95,
    dominantMarketType: "match",
    topEntity: "Manchester City",
    activeSignals: 2,
  },
  {
    id: "hot-barcelona",
    city: "Barcelona",
    country: "Spain",
    region: "Spain",
    league: "La Liga",
    x: 34,
    y: 66,
    intensity: 68,
    dominantMarketType: "match",
    topEntity: "Barcelona",
    activeSignals: 1,
  },
  {
    id: "hot-leverkusen",
    city: "Leverkusen",
    country: "Germany",
    region: "Germany",
    league: "Bundesliga",
    x: 58,
    y: 44,
    intensity: 74,
    dominantMarketType: "transfer",
    topEntity: "Bayer Leverkusen",
    activeSignals: 1,
  },
  {
    id: "hot-milan",
    city: "Milan",
    country: "Italy",
    region: "Italy",
    league: "Serie A",
    x: 62,
    y: 56,
    intensity: 61,
    dominantMarketType: "transfer",
    topEntity: "AC Milan",
    activeSignals: 1,
  },
  {
    id: "hot-naples",
    city: "Naples",
    country: "Italy",
    region: "Italy",
    league: "Serie A",
    x: 72,
    y: 66,
    intensity: 64,
    dominantMarketType: "transfer",
    topEntity: "Napoli",
    activeSignals: 1,
  },
  {
    id: "hot-paris",
    city: "Paris",
    country: "France",
    region: "France",
    league: "Ligue 1",
    x: 36,
    y: 48,
    intensity: 70,
    dominantMarketType: "match",
    topEntity: "Paris Saint-Germain",
    activeSignals: 3,
  },
];

export function getDashboardData(): DashboardData {
  return { signals, matchMovers, transferMovers, predictionMarkets, news, injuries, hotspots };
}
